#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

max_upload_size=50
auth_secret=$(ynh_string_random --length=32)
ynh_app_setting_set --key=auth_secret --value="$auth_secret"

ynh_app_setting_set --key=max_upload_size --value=$max_upload_size

email_smtp_host=$(cat /etc/yunohost/current_host)
email_smtp_user="$app"
email_smtp_password="$mail_pwd"
email_smtp_port=587
storage_driver=$storage_driver

mail_user="no-reply"
ynh_app_setting_set --key="mail_user" --value="$mail_user"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# INSTALLATION
#=================================================
ynh_script_progression "Adding $app's dependencies..."

pushd "$install_dir"
	ynh_hide_warnings corepack enable && COREPACK_ENABLE_DOWNLOAD_PROMPT=0 corepack prepare pnpm@latest --activate
	ynh_exec_as_app NODE_OPTIONS="--max-old-space-size=4096" pnpm install --frozen-lockfile

ynh_script_progression "Building $app..."
    ynh_exec_as_app NODE_OPTIONS="--max-old-space-size=4096" NX_DAEMON=false NX_DISABLE_NX_CACHE=true pnpm run editor-ext:build
    ynh_exec_as_app NODE_OPTIONS="--max-old-space-size=4096" NX_DAEMON=false NX_DISABLE_NX_CACHE=true pnpm run server:build
    ynh_exec_as_app NODE_OPTIONS="--max-old-space-size=4096" NX_DAEMON=false NX_DISABLE_NX_CACHE=true pnpm run client:build
popd


#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="$app" 

yunohost service add "$app" --description="Docmost" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

ln -s "$data_dir" "$install_dir/data"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"
ynh_systemctl --service=postfix --action="restart"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
